# fiber configuration
# Defaults are shown, commented out
# Some values have no defaults and must be filled in
[node]
genesis_signature_str = "eb10468d10054d15f2b6f8946cd46797779aa20a7617ceb4be884189f219bc9a164e56a5b9f7bec392a804ff3740210348d73db77a37adb542a8e08d429ac92700"
genesis_address_str = "UFQ8kZjnwQi8Qa48kXvFQ5GetUDZqgh7LH"
blockchain_pubkey_str = "032b0aa6ef66788954d432691dd7e11ef1a10846a86fba1903d802ee93c832a1bd"
blockchain_seckey_str = ""
genesis_timestamp = 1426562704
# genesis_coin_volume = 100e12
default_connections = [
    "118.178.135.93:6000",
    "47.88.33.156:6000",
    "121.41.103.148:6000",
    "120.77.69.188:6000",
    "104.237.142.206:6000",
    "176.58.126.224:6000",
    "172.104.85.6:6000",
    "139.162.7.132:6000",
    
]
peer_list_url = "https://downloads.skycoin.net/blockchain/peers.txt"
#port = 6000
#web_interface_port = 6420

[build]
version = "0.24.1"
#build = ""
#commit = ""

[visor]
#max_coin_supply = 1e8
#distribution_addresses_total = 100
#initial_unlocked_count = 25
#unlock_addresss_rate = 5
#unlocked_time_internal = 60 * 60 * 24 * 365
#max_droplet_precision = 3
#default_max_block_size = 32 * 1024
distribution_addresses = [
"eZjwb8g8N4Vev1yPuzcSnh78AgJV6SGHFK",
"xSsKwLUAcrFbW97Uc87UQq6zcCvQDmm1gN",
"rdbWZL2jGGp7thg4YNvZ3okxsYpxG4ztg1",
"2e6JPoQf4vzjCNjdtoVFQTuaAiCGwH4Y55C",
"mj6PMjsQDy2CPsqYqjXmT8HUzwFzWJ8rJt",
"zWHV3z8VRAsvUzgMJG2NmnKmG1DjQTxxa5",
"FYne2xrqvUwqgey62neJ3muRDuT9D3tLp3",
"J1t76VTFtCahWyYho2mEykbqvtqp8cAGnR",
"2JUUijX6WD3NCV4CRY4EhzAo9sMQ1Ua9UwZ",
"7BbazN2fAxU4zqdq9NcpB2gTjxNDtYQFep",
"2jvuMseFnaTxKCD7LKqQtbsdTG2ykqFo7YZ",
"fZbFU9dxwWDotRbnwu8rqMqHnTaybDe7Pr",
"AHPdavUS2189WDwHQgrGmNPLE5JFfCLzE9",
"22fEpMTRdVB5g9gFuJjQvhBiZK3h67z3NVZ",
"un66r3g4jfoGHiFQx8A7Y6G6tjScUUz5MS",
"22pP5Xz1U8Ri6XkiHxfp52LujiCDXDgRU6R",
"VCuc9RXPb4iYysynYvVECnqGcZDGzZt9q7",
"hUKoybfJtTMC9QbT1SSqCGJB1a4UDnW1cB",
"2EKNvNv2sg2zH6M3fCsP74sDjXu5RGDhVBG",
"SJYvLbeqjgX4xkQo6stCAbT12NtXSAkssn",
"2CVbeXD7kfaQ3rCKw1BkvyF2rdAvwLfneGS",
"233CA5qhMrQL6bUVtyXegJfGYUcXRgjmoiy",
"2N9j8SdmhuAcUSWPk7spVCcTGLYFjQnXyA2",
"241d7CGiDMTnBz9kSSwc7kS9cg44ppbBj4o",
"rZC69jgM3RccLXNHVaz6rvEzJ4Zivn4AkR",
"VG41kWMQmvpJaxCYA7cThzVpCZ5VyzxzR6",
"5Jg7K7X6cqzFah8CEsWvrhShAdQTDiXm3D",
"2NbekABazbCTRUwANiSUCgYsgVNNULLu6Es",
"oseuGSu8uA5nPjaymznDgtjdemt4w2v1d1",
"2CqHrgmvdzioz2gA8KARTN3DxaWbHxD8L8Q",
"GWueTCnhcmotaFsRciJhDdoC4gu1TQwXZT",
"2Aj3ttHErn6ZTfbVap6daLevxpRSby6s7fQ",
"GhLT7XudyCP9L7zgB3dypQVXBfur4hQJjR",
"nTv3PvJvfE4rBxEyNdxSofVkCGZdzFhuFa",
"cKGyuyweDraXqnV3DDoFL54R1edHKrJ38U",
"CtxknfpLs8XCJbhFmh6mSHb4D6WYrpqkEp",
"2T4C6e9aTgn4neZCXAKdZUdTbBidePk3Ars",
"2UvLUqxwT7UNyNcrzaNCYxbhF5Neze6yc5N",
"eXLdnMUqXyQGWrsBMgrVGHLHo9LhMzXj6Z",
"ocomNYyYBeNm3GPVz1RjwZyMqkdN3i6zhw",
"wPKhiU9SYUiZSK6Yk56Ah94CLcVvqx2QF8",
"2fmueDWXi3vJ48Ln4NNTSG6eup6CowZCnpQ",
"yBhTEKUALUqSh3dSvMkDR5FYDVnQs8agd7",
"2DZPnKFo8LcCLw2z4FScSqfaks3kqGnAatH",
"cFzsdxqjKjhFWiQNZ97mykAXvcBiNzEac9",
"275QJFex4oEKKhUR9sVEgwEevSGaMgUoAr2",
"2BWyjibMwcD4SWzpxJTYe9hYNhQgJfTQb6n",
"2JA8Ei73EN4bGWoNn4Jdujt8GDWrX5J1yNB",
"ZMUcfRGHeoLGzDyHwAjxXVC9swbS133SoC",
"MDkXrv93axi7czJp5hghgSxwyJ1bTCGQhy",
"g3pDwboPbKHyS4DJ3piZdr2r8KK7qVybXf",
"ZVzTrvUbxApQkWEkWq3yqfBfztUfW5vKwP",
"2UznikdMYCBZUiV8eAUygt5UCw613KsFmyi",
"3nGD5xavnRn87GgwK3GS8HwxvZ88ebXnGc",
"BiWnLzR5SPmbNYtBNKVBU2Z2BKUDZExwb1",
"28DUeW3uC3NXCLv3GfMLb5W2vnVN4wkrARp",
"yhJCQSGuQoVPc2LQSfd1nE1hL8kqTRDRRQ",
"HdjZsdu3jcmtTCWzZ99jDa3Y2i9w3KVU2P",
"EuteC1vAuz8q1tXrMqqjyVEYEeDMSuzaFH",
"SNJkc6eNx6Le1QaE2KP9jsZx7ETp6ATLZS",
"2GPCcJPPC1Lp977BwckXFSDXAoTADHYq5Kg",
"nPsFcPsm6GEqjvhKQTymATuABDYLQAig5a",
"GKQxkaShcij82bAKeZbCRZxzebkUsQTuif",
"2QJrG5u8tSB9XztHv8H8r6PRNspvSf8EaqR",
"o1XDGmq2MkBGtdZX3mvw31RGisR3g6diUy",
"Uu1o7Ridb29gS5FwWrVA8r3hjSGnS2Qpis",
"QzVZZFbpWgRZRccjRUrgqHNPd8uGH4wWs5",
"MHivapHxN47JZr7v44U5tL8TSGYPVvRo9o",
"29zMongabk63DUn1HmVUJhea862DCCs9Kiw",
"21KxZwc63JYSAfBG2Z7jWULdonXJ27attJP",
"NtCE1urnwKfwgHk3L8v4aknSxKZAbKNhLC",
"WvLwEtmoJUEPPaz2DcCYXRy9j32gqfwMUk",
"2F94Bet5bV4r6AuWMetcdstwH32wVwAXtMq",
"2iWDqN1jdSTsrQNcJTKfdQCEhoEgJkeyFGE",
"1EUqEBDYctNuUVHA2riQ49ioJVMfUvv2w2",
"RZAUKzXxmX9FiRyMgk8nUj2GPUMfTTLkg1",
"knMTrbWkqMaPanRTuvpQzFYN1ooviZ57wR",
"2SakgsmRYgiBkunETidzJTyENMtkdZj7MrP",
"2FEr6xQfNGFneimP7tywhZ3TjX6eZYXVXQa",
"kw36cLyRPciXW8gmRo12hXoGeVhep4CoQC",
"sL3RgVKrxPcfF6Ja1TBY3VYLTstAyhjd8v",
"dopMaLXpee7t4TD1y1Wo4iRBqErikgFGJP",
"2AHeWqHopEKZT262LXRxepU3ooZF9vYSRJE",
"cSthsm6JHu7JdMWNrzrzBjsGnkJpYwsEEk",
"rz9cXngg8eDssR9qfRuF4fzcfe1dktCUZ2",
"7UzPhWqL9oaxBuk84Zud3WWscoThxyEgvy",
"TjSsRg8HAWMiCFU91nfw6njZ3c81bdfHAu",
"ZdBesshBQdBbk5oZTZLN6ekuihBFcyk61G",
"4FXKFeV38src6hVorswB9kEfneABoa9ae3",
"JFR2LdLu18b4ywqoPsoqS1cZjW6WNJioBk",
"2Uj98Q8nfNAeRvVC1CME2pVkDX7znmSm1ZG",
"4tHyWvqa3pBmzXfJRPRKUZ4YePznvp5Guo",
"c8woDuthjenfymXiwYZSvqWAB71yPNawu6",
"22stmS4eyFF1zeNieaAoYKPRiVB1wmxenvm",
"b8SECsjHFLhrJAvDo92oDq9cLEUXk7EBMH",
"2BBHUuKaqbutkQreGcvgRMUKxAMJrbsaK8x",
"2fRCN3WuPDPG3585SqGf3oMR9c5Uj4XqFtv",
"2Vj8jxsL1uXdLQT3iFsub5Y2Vy4vsJraKCp",
"2PbZCF1HEfquVavTPxgffDeRgrrYFueQVRG",
"A1DeRXNpKXmqiaJFRN7Q3gh7kFdspZmpeX"
]
